server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-13.railway.app:7064/railway
    username: postgres
    password: SOQyXFocMyVukojw2ApG
  liquibase:
    change-log: classpath:db/changelog/db-changelog.yml
