spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-13.railway.app:7064/railway
    username: postgres
    password: SOQyXFocMyVukojw2ApG
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db-changelog.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 933264737803-31btvv2jlp21tbtmmfi7651ojohfllto.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 1446197359529099
            client-secret: c2ac5a3736e084454dbfb1b6b86a11cd

cloud:
  aws:
    region:
      static: eu-north-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA3Z4LAPLEORQEPG7Q
      secret-key: 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

fixt:
  base-url: http://localhost:8080/api

time-travel:
  enabled: false
  instant: 2022-09-01T12:00:00.00Z
  zone: UTC
